// Code generated by mfjson for marshaling/unmarshaling. DO NOT EDIT.
// https://github.com/myfantasy/json

package strategies

import (
	mfj "github.com/myfantasy/json"
)
func (obj *TakeProfitSell) UnmarshalJSONTypeName() string {
	return "smp.strategies.take_profit_sell"
}

func init() {
	mfj.GlobalStructFactory.Add("smp.strategies.take_profit_sell", func() mfj.JsonInterfaceMarshaller { return &TakeProfitSell{} })
	mfj.GlobalStructFactory.AddNil("smp.strategies.take_profit_sell", func() mfj.JsonInterfaceMarshaller {
		var out *TakeProfitSell
		return out
	})
}
