// Code generated by mfjson for marshaling/unmarshaling. DO NOT EDIT.
// https://github.com/myfantasy/json

package strategies

import (
	mfj "github.com/myfantasy/json"
)
func (obj *WingedSwingGroup) UnmarshalJSONTypeName() string {
	return "smp.strategies.winged_swing_group"
}

func init() {
	mfj.GlobalStructFactory.Add("smp.strategies.winged_swing_group", func() mfj.JsonInterfaceMarshaller { return &WingedSwingGroup{} })
	mfj.GlobalStructFactory.AddNil("smp.strategies.winged_swing_group", func() mfj.JsonInterfaceMarshaller {
		var out *WingedSwingGroup
		return out
	})
}
