// Code generated by mfjson for marshaling/unmarshaling. DO NOT EDIT.
// https://github.com/myfantasy/json

package strategies

import (
	mfj "github.com/myfantasy/json"
)
func (obj *WingedSwing) UnmarshalJSONTypeName() string {
	return "smp.strategies.winged_swing"
}

func init() {
	mfj.GlobalStructFactory.Add("smp.strategies.winged_swing", func() mfj.JsonInterfaceMarshaller { return &WingedSwing{} })
	mfj.GlobalStructFactory.AddNil("smp.strategies.winged_swing", func() mfj.JsonInterfaceMarshaller {
		var out *WingedSwing
		return out
	})
}
